"""empty message

Revision ID: b5156e9a29de
Revises: 9bd35d6de58b
Create Date: 2024-02-25 16:09:05.520275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5156e9a29de'
down_revision: Union[str, None] = '9bd35d6de58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_links', 'title')
    op.drop_column('news_links', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_links', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('news_links', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
