"""empty message

Revision ID: e6fc7858e090
Revises: b5156e9a29de
Create Date: 2024-02-25 17:09:18.409164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fc7858e090'
down_revision: Union[str, None] = 'b5156e9a29de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_links', sa.Column('create_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_links', 'create_at')
    # ### end Alembic commands ###
