"""empty message

Revision ID: f612bfaafc20
Revises: c2e369633543
Create Date: 2024-02-25 22:47:26.812499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f612bfaafc20'
down_revision: Union[str, None] = 'c2e369633543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.add_column('feedback', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feedback', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'user_id')
    op.drop_column('feedback', 'create_at')
    # ### end Alembic commands ###
